// Central, editable story configuration. Change names, lines, lengths and destinations here.
export const story = {
  site: {
    title: 'My Dream for Her',
    openingTitle: 'Our Future',
    subtitle: 'A life I hope we get to live.',
    from: 'Razal',
    to: 'Julian',
    storageKey: 'mdfh-proposal-v1',
  },
  sound: { enabledByDefault: false, volume: 0.35 },
  chapters: {
    distance: { vh: 420, places: ['India', 'Philippines'], lines: [
      'There was a distance between us.',
      'But somehow, you still became my favorite place.',
      'So I started imagining what it would feel like if one day the distance disappeared.',
    ] },
    ticket: { vh: 520, from: 'INDIA', to: 'PHILIPPINES', destination: 'JULIAN', note: 'seat: next to my heart · luggage: everything I wanted to tell you' },
    arrival: { vh: 620, lines: ['After all those miles…', '…I finally got to hold you.', 'And somehow, the first hug made every mile worth it.'] },
    dating: { vh: 820, captions: [
      'The little things.',
      'The ordinary days I somehow wanted forever.',
      'Getting caught in the rain, on purpose.',
      'Nothing spectacular.',
      'And yet, everything felt special.',
      'Laughing at nothing at all.',
      'Talking until the stars got tired.',
      'Sharing everything, even the last bite.',
    ] },
    proposal: { vh: 520 },
    wedding: { vh: 620, lines: ["We didn't just promise to love each other.", 'We promised to build a life together.'] },
    home: { vh: 720, rooms: [
      { id: 'bedroom', caption: 'Slow mornings.', note: 'Five more minutes. Then five more.' },
      { id: 'kitchen', caption: 'Cooking together.', note: 'You taste, I stir, we both pretend it’s perfect.' },
      { id: 'living', caption: 'Movie nights.', note: 'You’ll fall asleep halfway. I’ll watch you instead.' },
      { id: 'balcony', caption: 'Talking until midnight.', note: 'Same stars we used to look at from two countries.' },
      { id: 'garden', caption: 'Flowers for no particular reason.', note: 'Because it’s Tuesday. Because it’s you.' },
    ] },
    family: { vh: 900, daughter: 'OUR DAUGHTER', son: 'OUR SON', captions: ['First steps.', 'Birthdays.', 'Bedtime stories.', 'Our loud, warm table.'] },
    growing: { vh: 900, lines: ['We blinked.', 'And somehow, they had grown up.'] },
    lettingGo: { vh: 640, lines: ['We spent years building a family.', 'And then one day…', '…the house became quiet again.'], quote: '“Looks like it’s just us again.”' },
    travel: { vh: 1000, lines: ['After spending so long dreaming about one journey…', '…we spent the rest of our lives making many more.'],
      destinations: [
        { id: 'philippines', name: 'Philippines', note: 'Where it all began. Again.' },
        { id: 'india', name: 'India', note: 'Showing you every street of my childhood.' },
        { id: 'paris', name: 'Paris', note: 'Getting lost on purpose.' },
        { id: 'japan', name: 'Japan', note: 'Cherry blossoms in your hair.' },
        { id: 'alps', name: 'Switzerland', note: 'A slow train and your head on my shoulder.' },
        { id: 'venice', name: 'Italy', note: 'Dinner by the water. Dancing badly.' },
      ] },
    time: { vh: 640 },
    final: { vh: 660, lines: ['After everything…', 'After every place…', 'After every dream…', 'After all the years…'],
      message: 'My favorite part was simply growing old beside you.' },
  },
  proposal: {
    name: 'JULIAN…',
    question: 'WILL YOU MARRY ME?',
    lines: ["I don't know exactly what the future will look like.", 'But whenever I imagine mine…', '…I keep finding you in it.'],
    yesLabel: 'YES ❤',
    notYetLabel: 'NOT YET',
    yesText: 'SHE SAID YES.',
    yesLine: "And suddenly, the next page didn't feel like a dream anymore.",
    notYetText: "Then I'll wait.",
    notYetLine: 'Some dreams are worth giving time.',
  },
  ending: { end: 'THE END', maybe: 'OR MAYBE…', beginning: 'JUST THE BEGINNING.', dedication: 'For every version of tomorrow where I get to find you again.' },
};
export type Choice = 'yes' | 'notyet' | null;
